platform :ios, '7.0' 

target "Doktor TV" do
	pod "TDMSwitchTableViewCell", :git => "https://github.com/duemunk/TDMSwitchTableViewCell.git"
	pod "DMTestSettings", :git => "https://github.com/duemunk/DMTestSettings.git"
	pod "KeepLayout", :git => "https://github.com/duemunk/KeepLayout.git"
	pod "JMStaticContentTableViewController", :git => "https://github.com/duemunk/JMStaticContentTableViewController.git"
	pod "TDMScreenEdgePanGestureRecognizer", :git => "https://github.com/duemunk/TDMScreenEdgePanGestureRecognizer.git"
	pod "TDMZoomCollectionViewController", :git => "https://tobiasdm@bitbucket.org/tobiasdm/tdmzoomcollectionviewcontroller.git"
	pod "CocoaLumberjack"
	pod "iOS7Colors"
	pod "AFNetworking"
end